# Generated by Django 2.2.28 on 2022-06-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.CharField(max_length=50)),
                ('saddress', models.CharField(max_length=50)),
                ('smobile', models.IntegerField()),
                ('sgender', models.CharField(max_length=1)),
            ],
        ),
    ]
